export const EDITOR_CHANGE_ADD = 'EDITOR_CHANGE_ADD';

export const EDITOR_VALUE_SET = 'EDITOR_VALUE_SET';

export const PLAYBACK_STARTING_TIME_RESET = 'PLAYBACK_STARTING_TIME_RESET';

export const PLAYBACK_PLAYING_SET = 'PLAYBACK_PLAYING_SET';

export const FETCH_CHALLENGE_DATA_START = 'FETCH_CHALLENGE_DATA_START'

export const FETCH_CHALLENGE_DATA_SUCCESS = 'FETCH_CHALLENGE_DATA_SUCCESS';

export const FETCH_CHALLENGE_DATA_ERROR = 'FETCH_CHALLENGE_DATA_ERROR';

export const SET_CURRENT_LANGUAGE = 'SET_CURRENT_LANGUAGE';