export const EDITOR_CHANGE_EVENT = 'EDITOR_CHANGE_EVENT';

export const EDITOR_VALUE_SET = 'EDITOR_VALUE_SET';

export const PLAYBACK_EVENTS_SET = 'PLAYBACK_EVENTS_SET';

export const PLAYBACK_PLAYING_SET = 'PLAYBACK_PLAYING_SET';

export const TIMELINE_EVENT = 'TIMELINE_EVENT';

export const TIMELINE_RESET = 'TIMELINE_RESET';
