export const EDITOR_CHANGE_ADD = 'EDITOR_CHANGE_ADD';

export const EDITOR_VALUE_SET = 'EDITOR_VALUE_SET';

export const PLAYBACK_STARTING_TIME_RESET = 'PLAYBACK_STARTING_TIME_RESET';

export const PLAYBACK_PLAYING_SET = 'PLAYBACK_PLAYING_SET';

export const FETCH_CHALLENGE_DATA_START = 'FETCH_CHALLENGE_DATA_START'

export const FETCH_CHALLENGE_DATA_SUCCESS = 'FETCH_CHALLENGE_DATA_SUCCESS';

export const FETCH_CHALLENGE_DATA_ERROR = 'FETCH_CHALLENGE_DATA_ERROR';

export const SET_CURRENT_LANGUAGE = 'SET_CURRENT_LANGUAGE';

export const UPDATE_CURRENT_TESTS = 'UPDATE_CURRENT_TESTS';

export const RESET_CURRENT_TESTS = 'RESET_CURRENT_TESTS';

export const RUN_SAMPLE_TESTS_START = 'RUN_SAMPLE_TESTS_START';

export const RUN_SAMPLE_TESTS_SUCCESS = 'RUN_SAMPLE_TESTS_SUCCESS';

export const RUN_SAMPLE_TESTS_ERROR = 'RUN_SAMPLE_TESTS_ERROR';

export const SUBMIT_CHALLENGE_START = 'SUBMIT_CHALLENGE_START';

export const SUBMIT_CHALLENGE_SUCCESS = 'SUBMIT_CHALLENGE_SUCCESS';

export const SUBMIT_CHALLENGE_ERROR = 'RUN_SAMPLE_CHALLENGE_ERROR';
